meta-lead-ads-package/main/default/objects/Meta_Lead_Log__c/Meta_Lead_Log__c.object-meta.xml
<CustomObject>
    <label>Meta Lead Log</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meta Lead Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meta-lead-ads-package/main/default/objects/Meta_Lead_Log__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

meta-lead-ads-package/main/default/classes/MetaLeadRetryBatch.cls
/**
 * MetaLeadRetryBatch
 * 
 * Scheduled Batch job to automatically retry failed Meta Lead Graph API callouts.
 * This ensures temporary Graph API errors or token issues don't result in permanent data loss.
 */
public class MetaLeadRetryBatch implements Database.Batchable<sObject>, Schedulable {
    
    // Schedulable method allows scheduling via UI
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new MetaLeadRetryBatch(), 50);
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        // Query failed logs from the last 7 days
        return Database.getQueryLocator([
            SELECT Id
            FROM Meta_Lead_Log__c
            WHERE Processing_Status__c = 'Failed'
            AND CreatedDate = LAST_N_DAYS:7
        ]);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Id> logIds = new List<Id>();
        for (SObject obj : scope) {
            logIds.add((Id)obj.get('Id'));
        }
        
        if (!logIds.isEmpty() && !Test.isRunningTest()) {
            // Hand off to our newly bulkified Queueable class
            // (Limit: 1 Queueable enqueue allowed per batch execute)
            System.enqueueJob(new MetaLeadCalloutJob(logIds));
        }
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('MetaLeadRetryBatch completed.');
    }
}