meta-lead-ads-package/main/default/objects/Meta_Auth_Token__c/Meta_Auth_Token__c.object-meta.xml
<CustomObject>
    <label>Meta Auth Token</label>
    <nameField>
        <label>Meta_Auth_Token__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Auth Token</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meta-lead-ads-package/main/default/objects/Meta_Auth_Token__c/fields/User_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>User_Access_Token__c</fullName>
    <label>User Access Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

meta-lead-ads-package/main/default/objects/Meta_Page__c/Meta_Page__c.object-meta.xml
<CustomObject>
    <label>Meta Page</label>
    <nameField>
        <label>Meta Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meta Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meta-lead-ads-package/main/default/objects/Meta_Page__c/fields/Page_ID__c.field-meta.xml
<CustomField>
    <fullName>Page_ID__c</fullName>
    <externalId>true</externalId>
    <label>Page ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

meta-lead-ads-package/main/default/objects/Meta_Page__c/fields/Page_Name__c.field-meta.xml
<CustomField>
    <fullName>Page_Name__c</fullName>
    <label>Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

meta-lead-ads-package/main/default/classes/MetaPageServiceTest.cls
@isTest
private class MetaPageServiceTest {
    private class PageMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody('{"data":[{"id":"111","name":"Page1","access_token":"token1"}]}');
            return res;
        }
    }

    @isTest
    static void testSyncPages() {
        insert new Meta_Auth_Token__c(Name = 'Facebook Token', User_Access_Token__c = 'mock_user_token');
        Test.setMock(HttpCalloutMock.class, new PageMock());
        
        Test.startTest();
        List<Meta_Page__c> pages = MetaPageService.syncPages();
        Test.stopTest();
        
        System.assert(pages.size() > 0);
    }

    @isTest
    static void testGetPages() {
        insert new Meta_Page__c(Page_ID__c = '111', Page_Name__c = 'Page1', Active__c = true);
        
        Test.startTest();
        List<Meta_Page__c> pages = MetaPageService.getPages();
        Test.stopTest();
        
        System.assertEquals(1, pages.size());
    }
}