meta-lead-ads-package/main/default/objects/Meta_Campaign_Analytics__c/Meta_Campaign_Analytics__c.object-meta.xml
<CustomObject>
    <label>Meta Campaign Analytics</label>
    <pluralLabel>Meta Campaign Analytics</pluralLabel>
    <nameField>
        <displayFormat>MCA-{000000}</displayFormat>
        <label>Campaign Analytics Record</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meta-lead-ads-package/main/default/objects/Meta_Campaign_Analytics__c/fields/Ad_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Ad_Account_Id__c</fullName>
    <label>Ad Account ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

meta-lead-ads-package/main/default/classes/AnalyticsScheduler.cls
public with sharing class AnalyticsScheduler implements Schedulable {
    
    public String adAccountId;

    public AnalyticsScheduler() {}
    
    public AnalyticsScheduler(String adAccountId) {
        this.adAccountId = adAccountId;
    }

    public void execute(SchedulableContext sc) {
        String targetAccId = this.adAccountId;
        if (String.isBlank(targetAccId)) {
            List<Meta_Campaign_Analytics__c> lastRecs = [SELECT Ad_Account_Id__c FROM Meta_Campaign_Analytics__c WHERE Ad_Account_Id__c != null LIMIT 1];
            if (!lastRecs.isEmpty()) {
                targetAccId = lastRecs[0].Ad_Account_Id__c;
            }
        }

        if (String.isNotBlank(targetAccId)) {
            executeAsync(targetAccId);
        }
    }

    @future(callout=true)
    public static void executeAsync(String adAccountId) {
        if (String.isNotBlank(adAccountId)) {
            // Callouts MUST occur before DML in Salesforce Apex
            InsightsSyncService.syncInsightsData(adAccountId, 'last_30d');
            CampaignSyncService.syncCampaignData(adAccountId);
        }
    }
}